In [1]:
from sklearn.datasets import fetch_20newsgroups
#Choosing categories we require 
categories = ['alt.atheism','soc.religion.christian','comp.graphics','sci.med']
#Will take data from the folder train/test
news_train = fetch_20newsgroups(subset='train',categories=categories,shuffle=True)
news_test = fetch_20newsgroups(subset='test',categories=categories,shuffle=True)

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
text = ["The quick brown fox jumped over the lazy dog.","The dog.","The fox"]
vector = CountVectorizer()
vector.fit(text)
print("Print Vocabulary: "+ str(vector.vocabulary_)+'\n]n')
vector.get_feature_names()
print("Features names:" + str(vector.get_feature_names())+'\n\n')
counts = vector.transform(text)
print("Printing count:"+'\n'+str(counts.toarray()))

Print Vocabulary: {'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}
]n
Features names:['brown', 'dog', 'fox', 'jumped', 'lazy', 'over', 'quick', 'the']


Printing count:
[[1 1 1 1 1 1 1 2]
 [0 1 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 1]]


In [3]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_tf = count_vect.fit_transform(news_train.data)
X_train_tf.shape

(2257, 35788)

In [4]:
from sklearn.feature_extraction.text import TfidfTransformer
#create the transform
vectorizer = TfidfTransformer()
vectorizer.fit(counts)
print('Learning Frequency of all features:'+ str(vectorizer.idf_)+'\n\n')

freq = vectorizer.transform(counts)
print('Transforming the matrix based on the learnt frequencies or weight:\n\n'+ str(freq.toarray()))


Learning Frequency of all features:[1.69314718 1.28768207 1.28768207 1.69314718 1.69314718 1.69314718
 1.69314718 1.        ]


Transforming the matrix based on the learnt frequencies or weight:

[[0.36388646 0.27674503 0.27674503 0.36388646 0.36388646 0.36388646
  0.36388646 0.42983441]
 [0.         0.78980693 0.         0.         0.         0.
  0.         0.61335554]
 [0.         0.         0.78980693 0.         0.         0.
  0.         0.61335554]]


In [6]:
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_tf)
X_train_tfidf.shape

(2257, 35788)

In [13]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=10)
clf1 = clf.fit(X_train_tfidf,news_train.target)
X_test_tf = count_vect.transform(news_test.data)
X_test_tfidf = tfidf_transformer.transform(X_test_tf)
predicted = clf1.predict(X_test_tfidf)

In [14]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(news_test.target,predicted))
print(metrics.classification_report(news_test.target,predicted,target_names=news_test.target_names)),metrics.confusion_matrix(news_test.target,predicted)

Accuracy: 0.715046604527297
                        precision    recall  f1-score   support

           alt.atheism       0.66      0.66      0.66       319
         comp.graphics       0.69      0.80      0.74       389
               sci.med       0.69      0.58      0.63       396
soc.religion.christian       0.80      0.81      0.80       398

              accuracy                           0.72      1502
             macro avg       0.71      0.71      0.71      1502
          weighted avg       0.71      0.72      0.71      1502



(None,
 array([[211,  29,  36,  43],
        [ 18, 312,  46,  13],
        [ 56,  85, 230,  25],
        [ 33,  23,  21, 321]], dtype=int64))